# .github/workflows/cache.yml

name: CI Cache Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-2d7e95e
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/test-deps
          key: cache-2d7e95e

      - name: Show cache result
        run: echo "Cache hit:${{steps.cache-step.outputs.cache-hit}}"
